config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :employee_managements
  resources :customer_managements
  resources :products
  resources :sales_reportings
  resources :inventories
  root :to => 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/employee_management.rb
class EmployeeManagement < ApplicationRecord
end

app/controllers/employee_managements_controller.rb
class EmployeeManagementsController < ApplicationController
  before_action :set_employee_management, only: [:show, :edit, :update, :destroy]

  # GET /employee_managements
  # GET /employee_managements.json
  def index
    @employee_managements = EmployeeManagement.all
  end

  # GET /employee_managements/1
  # GET /employee_managements/1.json
  def show
  end

  # GET /employee_managements/new
  def new
    @employee_management = EmployeeManagement.new
  end

  # GET /employee_managements/1/edit
  def edit
  end

  # POST /employee_managements
  # POST /employee_managements.json
  def create
    @employee_management = EmployeeManagement.new(employee_management_params)

    respond_to do |format|
      if @employee_management.save
        format.html { redirect_to @employee_management, notice: 'Employee management was successfully created.' }
        format.json { render :show, status: :created, location: @employee_management }
      else
        format.html { render :new }
        format.json { render json: @employee_management.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employee_managements/1
  # PATCH/PUT /employee_managements/1.json
  def update
    respond_to do |format|
      if @employee_management.update(employee_management_params)
        format.html { redirect_to @employee_management, notice: 'Employee management was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee_management }
      else
        format.html { render :edit }
        format.json { render json: @employee_management.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employee_managements/1
  # DELETE /employee_managements/1.json
  def destroy
    @employee_management.destroy
    respond_to do |format|
      format.html { redirect_to employee_managements_url, notice: 'Employee management was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee_management
      @employee_management = EmployeeManagement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_management_params
      params.require(:employee_management).permit(:employee, :clockin, :clockout)
    end
end

app/helpers/employee_managements_helper.rb
module EmployeeManagementsHelper
end

app/views/employee_managements/_form.html.erb
<%= form_with(model: employee_management, local: true) do |form| %>
  <% if employee_management.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee_management.errors.count, "error") %> prohibited this employee_management from being saved:</h2>

      <ul>
      <% employee_management.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :employee %>
    <%= form.text_field :employee, id: :employee_management_employee %>
  </div>

  <div class="field">
    <%= form.label :clockin %>
    <%= form.text_field :clockin, id: :employee_management_clockin %>
  </div>

  <div class="field">
    <%= form.label :clockout %>
    <%= form.text_field :clockout, id: :employee_management_clockout %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/employee_managements/edit.html.erb
<h1>Editing Employee Management</h1>

<%= render 'form', employee_management: @employee_management %>

<%= link_to 'Show', @employee_management %> |
<%= link_to 'Back', employee_managements_path %>

app/views/employee_managements/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Employee Managements</h1>

<br>
<br>

<table>
  <thead>
    <tr>
      <th>Employee</th>
      <th>Clockin</th>
      <th>Clockout</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employee_managements.each do |employee_management| %>
      <tr>
        <td><%= employee_management.employee %></td>
        <td><%= employee_management.clockin %></td>
        <td><%= employee_management.clockout %></td>
        <td><%= link_to 'Show', employee_management %></td>
        <td><%= link_to 'Edit', edit_employee_management_path(employee_management) %></td>
        <td><%= link_to 'Destroy', employee_management, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<br>
<br>


<%= link_to 'New Employee Management', new_employee_management_path,
    class: 'ui-btn ui-corner-all ui-btn-icon-left ui-icon-plus'
%>

<br>

<%= link_to 'Go back to Home', root_path,
    class: 'ui-btn ui-corner-all ui-btn-icon-left ui-icon-home'
%>

app/views/employee_managements/new.html.erb
<h1>New Employee Management</h1>

<%= render 'form', employee_management: @employee_management %>

<%= link_to 'Back', employee_managements_path %>

app/views/employee_managements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Employee:</strong>
  <%= @employee_management.employee %>
</p>

<p>
  <strong>Clockin:</strong>
  <%= @employee_management.clockin %>
</p>

<p>
  <strong>Clockout:</strong>
  <%= @employee_management.clockout %>
</p>

<%= link_to 'Edit', edit_employee_management_path(@employee_management) %> |
<%= link_to 'Back', employee_managements_path %>