config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :employee_managements
  resources :customer_managements
  resources :products
  resources :sales_reportings
  resources :inventories
  root :to => 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/customer_management.rb
class CustomerManagement < ApplicationRecord
end

app/controllers/customer_managements_controller.rb
class CustomerManagementsController < ApplicationController
  before_action :set_customer_management, only: [:show, :edit, :update, :destroy]

  # GET /customer_managements
  # GET /customer_managements.json
  def index
    @customer_managements = CustomerManagement.all
  end

  # GET /customer_managements/1
  # GET /customer_managements/1.json
  def show
  end

  # GET /customer_managements/new
  def new
    @customer_management = CustomerManagement.new
  end

  # GET /customer_managements/1/edit
  def edit
  end

  # POST /customer_managements
  # POST /customer_managements.json
  def create
    @customer_management = CustomerManagement.new(customer_management_params)

    respond_to do |format|
      if @customer_management.save
        format.html { redirect_to @customer_management, notice: 'Customer management was successfully created.' }
        format.json { render :show, status: :created, location: @customer_management }
      else
        format.html { render :new }
        format.json { render json: @customer_management.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customer_managements/1
  # PATCH/PUT /customer_managements/1.json
  def update
    respond_to do |format|
      if @customer_management.update(customer_management_params)
        format.html { redirect_to @customer_management, notice: 'Customer management was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer_management }
      else
        format.html { render :edit }
        format.json { render json: @customer_management.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customer_managements/1
  # DELETE /customer_managements/1.json
  def destroy
    @customer_management.destroy
    respond_to do |format|
      format.html { redirect_to customer_managements_url, notice: 'Customer management was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer_management
      @customer_management = CustomerManagement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_management_params
      params.require(:customer_management).permit(:customer, :amount_paid)
    end
end

app/helpers/customer_managements_helper.rb
module CustomerManagementsHelper
end

app/views/customer_managements/_form.html.erb
<%= form_with(model: customer_management, local: true) do |form| %>
  <% if customer_management.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(customer_management.errors.count, "error") %> prohibited this customer_management from being saved:</h2>

      <ul>
      <% customer_management.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :customer %>
    <%= form.text_field :customer, id: :customer_management_customer %>
  </div>

  <div class="field">
    <%= form.label :amount_paid %>
    <%= form.text_field :amount_paid, id: :customer_management_amount_paid %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/customer_managements/edit.html.erb
<h1>Editing Customer Management</h1>

<%= render 'form', customer_management: @customer_management  %>

<%= link_to 'Show', @customer_management %> |
<%= link_to 'Back', customer_managements_path %>

app/views/customer_managements/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Customer Managements</h1>

<br>
<br>

<table>
  <thead>
    <tr>
      <th>Customer</th>
      <th>Amount paid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customer_managements.each do |customer_management| %>
      <tr>
        <td><%= customer_management.customer %></td>
        <td><%= customer_management.amount_paid %></td>
        <td><%= link_to 'Show', customer_management %></td>
        <td><%= link_to 'Edit', edit_customer_management_path(customer_management)  %></td>
        <td><%= link_to 'Destroy', customer_management, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<br>

<%= link_to 'New Customer Management', new_customer_management_path,
    class: 'ui-btn ui-corner-all ui-btn-icon-left ui-icon-plus'
%>

<br>

<%= link_to 'Go back to Home', root_path,
    class: 'ui-btn ui-corner-all ui-btn-icon-left ui-icon-home'
%>

app/views/customer_managements/new.html.erb
<h1>New Customer Management</h1>

<%= render 'form', customer_management: @customer_management  %>

<%= link_to 'Back', customer_managements_path %>

app/views/customer_managements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Customer:</strong>
  <%= @customer_management.customer %>
</p>

<p>
  <strong>Amount paid:</strong>
  <%= @customer_management.amount_paid %>
</p>

<%= link_to 'Edit', edit_customer_management_path(@customer_management) %> |
<%= link_to 'Back', customer_managements_path %>