config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :employee_managements
  resources :customer_managements
  resources :products
  resources :sales_reportings
  resources :inventories
  root :to => 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/sales_reporting.rb
class SalesReporting < ApplicationRecord
end

app/controllers/sales_reportings_controller.rb
class SalesReportingsController < ApplicationController
  before_action :set_sales_reporting, only: [:show, :edit, :update, :destroy]

  # GET /sales_reportings
  # GET /sales_reportings.json
  def index
    @sales_reportings = SalesReporting.all
  end

  # GET /sales_reportings/1
  # GET /sales_reportings/1.json
  def show
  end

  # GET /sales_reportings/new
  def new
    @sales_reporting = SalesReporting.new
  end

  # GET /sales_reportings/1/edit
  def edit
  end

  # POST /sales_reportings
  # POST /sales_reportings.json
  def create
    @sales_reporting = SalesReporting.new(sales_reporting_params)

    respond_to do |format|
      if @sales_reporting.save
        format.html { redirect_to @sales_reporting, notice: 'Sales reporting was successfully created.' }
        format.json { render :show, status: :created, location: @sales_reporting }
      else
        format.html { render :new }
        format.json { render json: @sales_reporting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales_reportings/1
  # PATCH/PUT /sales_reportings/1.json
  def update
    respond_to do |format|
      if @sales_reporting.update(sales_reporting_params)
        format.html { redirect_to @sales_reporting, notice: 'Sales reporting was successfully updated.' }
        format.json { render :show, status: :ok, location: @sales_reporting }
      else
        format.html { render :edit }
        format.json { render json: @sales_reporting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales_reportings/1
  # DELETE /sales_reportings/1.json
  def destroy
    @sales_reporting.destroy
    respond_to do |format|
      format.html { redirect_to sales_reportings_url, notice: 'Sales reporting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sales_reporting
      @sales_reporting = SalesReporting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sales_reporting_params
      params.require(:sales_reporting).permit(:product, :quantity, :amount_paid)
    end
end

app/helpers/sales_reportings_helper.rb
module SalesReportingsHelper
end

app/views/sales_reportings/_form.html.erb
<%= form_with(model: sales_reporting, local: true) do |form| %>
  <% if sales_reporting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sales_reporting.errors.count, "error") %> prohibited this sales_reporting from being saved:</h2>

      <ul>
      <% sales_reporting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :product %>
    <%= form.text_field :product, id: :sales_reporting_product %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity, id: :sales_reporting_quantity %>
  </div>

  <div class="field">
    <%= form.label :amount_paid %>
    <%= form.text_field :amount_paid, id: :sales_reporting_amount_paid %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sales_reportings/edit.html.erb
<h1>Editing Sales Reporting</h1>

<%= render 'form', sales_reporting: @sales_reporting %>

<%= link_to 'Show', @sales_reporting %> |
<%= link_to 'Back', sales_reportings_path %>

app/views/sales_reportings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sales Reportings</h1>

<br>
<br>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Quantity</th>
      <th>Amount paid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sales_reportings.each do |sales_reporting| %>
      <tr>
        <td><%= sales_reporting.product %></td>
        <td><%= sales_reporting.quantity %></td>
        <td><%= sales_reporting.amount_paid %></td>
        <td><%= link_to 'Show', sales_reporting %></td>
        <td><%= link_to 'Edit', edit_sales_reporting_path(sales_reporting) %></td>
        <td><%= link_to 'Destroy', sales_reporting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<br>

<%= link_to 'New Sales Reporting', new_sales_reporting_path,
    class: 'ui-btn ui-corner-all ui-btn-icon-left ui-icon-plus'
%>

<br>

<%= link_to 'Go back to Home', root_path,
    class: 'ui-btn ui-corner-all ui-btn-icon-left ui-icon-home'
%>

app/views/sales_reportings/new.html.erb
<h1>New Sales Reporting</h1>

<%= render 'form', sales_reporting: @sales_reporting %>

<%= link_to 'Back', sales_reportings_path %>

app/views/sales_reportings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @sales_reporting.product %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @sales_reporting.quantity %>
</p>

<p>
  <strong>Amount paid:</strong>
  <%= @sales_reporting.amount_paid %>
</p>

<%= link_to 'Edit', edit_sales_reporting_path(@sales_reporting) %> |
<%= link_to 'Back', sales_reportings_path %>