config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :employee_managements
  resources :customer_managements
  resources :products
  resources :sales_reportings
  resources :inventories
  root :to => 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:product, :quantity, :unit_purchasing_price, :unit_selling_price, :supplier)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :product %>
    <%= form.text_field :product, id: :product_product %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity, id: :product_quantity %>
  </div>

  <div class="field">
    <%= form.label :unit_purchasing_price %>
    <%= form.text_field :unit_purchasing_price, id: :product_unit_purchasing_price %>
  </div>

  <div class="field">
    <%= form.label :unit_selling_price %>
    <%= form.text_field :unit_selling_price, id: :product_unit_selling_price %>
  </div>

  <div class="field">
    <%= form.label :supplier %>
    <%= form.text_field :supplier, id: :product_supplier %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<br>
<br>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Quantity</th>
      <th>Unit purchasing price</th>
      <th>Unit selling price</th>
      <th>Supplier</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.product %></td>
        <td><%= product.quantity %></td>
        <td><%= product.unit_purchasing_price %></td>
        <td><%= product.unit_selling_price %></td>
        <td><%= product.supplier %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<br>
<br>


<%= link_to 'New Product', new_product_path,
    class: 'ui-btn ui-corner-all ui-btn-icon-left ui-icon-plus'
%>

<br>

<%= link_to 'Go back to Home', root_path,
    class: 'ui-btn ui-corner-all ui-btn-icon-left ui-icon-home'
%>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @product.product %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @product.quantity %>
</p>

<p>
  <strong>Unit purchasing price:</strong>
  <%= @product.unit_purchasing_price %>
</p>

<p>
  <strong>Unit selling price:</strong>
  <%= @product.unit_selling_price %>
</p>

<p>
  <strong>Supplier:</strong>
  <%= @product.supplier %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>